version: 2

models:
  - name: fact_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

      - name: customer_name
        tests:
          - not_null

  - name: top_customers
    columns:
      - name: customer_name
        tests:
          - not_null